### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by cclauss** [tiepvupsu/zalo_landmark#2]
Python 3 treats TabErrors as syntax errors.

flake8 testing of https://github.com/tiepvupsu/zalo_landmark on Python 3.7.0

$ __time flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./src/zalo_utils.py:88:16: E999 TabError: inconsistent use of tabs and spaces in indentation
	if depth == 18:
               ^
1     E999 TabError: inconsistent use of tabs and spaces in indentation
1
```

**Comment by tiepvupsu** [comment]
Thank you, I fixed the issue. Now you can `python3 train.py` without this problem.
